### PR TITLE
chore: update leftover by mistake; from #49

### PR DESCRIPTION
**Pull request by Pranav-yadav**
- all of us missed to update this unknowingly; in #49

### CODE REVIEW

**Comment by Pranav-yadav** [comment]
#49 was merged unknowingly without updating this.
@0-vortex

**Review by 0-vortex — APPROVED** [review]
Good catch, LGTM! 👍

**Comment by Pranav-yadav** [comment]
@0-vortex I wanted to discuss some features with you & "Brian" and may be whole OpenSauced team ;), which I think might have a sky-high impact on the OpenSauced platform and its ecosystem and exponential growth in adoption.
I'm already a member of OpenSauced discord server. So, will you be able to create a _private chat_ there; for me to put forward the ideas and plans with mock-designs? 

ping @bdougie (sorry, I know you're too busy)

Note: This may sound too niche, but believe me, none of you will regret it.

**Comment by bdougie** [comment]
> @0-vortex I wanted to discuss some features with you & "Brian" and may be whole OpenSauced team ;), which I think might have a sky-high impact on the OpenSauced platform and its ecosystem and exponential growth in adoption. I'm already a member of OpenSauced discord server. So, will you be able to create a _private chat_ there; for me to put forward the ideas and plans with mock-designs?
> 
> ping @bdougie (sorry, I know you're too busy)
> 
> Note: This may sound too niche, but believe me, none of you will regret it.

Private chat is not necessary. Share in the contributor channel or considering using our API to build in a new repo. Open source FTW.

**Comment by Pranav-yadav** [comment]
@bdougie Definitely. I'm also Open Source Enthusiast and try to do most dev. things in Open. But, I'm sure you'll also agree on a part that initially some ideas can be kept private I.e. During _Ideation_ phase of new startup or some invention.

And, after spending enough amount of time on some idea, at least during _Ideation Phase_ I would like to keep it to limited reach since, "my idea itself has good potential of being a startup on it's own". I not bragging, or trying to sell something, I admire what OpenSauced is doing and you guys for building it.

I saw the potential in OpenSauced platform and ecosystem, hence..

I know you would like to keep all things public, but I think during initial phase of something (which has great potential) can be kept private, untill the actual *"Initial Commit"* is made...

I believe, in todays world an "idea/plan" is what most people seek.

Again, I'm genuinely interested in the platform, it's _not just that because I've applied for Octernship_, I literally saw the future w/ the idea together w/ OpenSauced platform.

FWIW, the idea/plan itself was one of my medium term goals (written in TODO list) _before even getting to know about OpenSauced_ through Octernship program. Because, I was busy with studies, I didn't start the execution.

Note: I'm not trying to sell something. And FWIW, I'm graduating as a "Computer Engineer" (with bachelor's degree) in 2-3 months i.e. In May/June this year. 😊

Cc: @0-vortex 

Thanks
Pranav

**Comment by 0-vortex** [comment]
> @bdougie Definitely. I'm also Open Source Enthusiast and try to do most dev. things in Open. But, I'm sure you'll also agree on a part that initially some ideas can be kept private I.e. During _Ideation_ phase of new startup or some invention.
> 
> And, after spending enough amount of time on some idea, at least during _Ideation Phase_ I would like to keep it to limited reach since, "my idea itself has good potential of being a startup on it's own". I not bragging, or trying to sell something, I admire what OpenSauced is doing and you guys for building it.
> 
> I saw the potential in OpenSauced platform and ecosystem, hence..
> 
> I know you would like to keep all things public, but I think during initial phase of something (which has great potential) can be kept private, untill the actual *"Initial Commit"* is made...
> 
> I believe, in todays world an "idea/plan" is what most people seek.
> 
> Again, I'm genuinely interested in the platform, it's _not just that because I've applied for Octernship_, I literally saw the future w/ the idea together w/ OpenSauced platform.
> 
> FWIW, the idea/plan itself was one of my medium term goals (written in TODO list) _before even getting to know about OpenSauced_ through Octernship program. Because, I was busy with studies, I didn't start the execution.
> 
> Note: I'm not trying to sell something. And FWIW, I'm graduating as a "Computer Engineer" (with bachelor's degree) in 2-3 months i.e. In May/June this year. 😊
> 
> Cc: @0-vortex 
> 
> Thanks
> Pranav

This is worthy of "the dropbox" story: https://www.quora.com/How-do-I-share-my-startup-ideas

Would argue that, if your idea is so valuable, you could create a private repo where you make a model/diagram of what you would be ideally building, and, outside of that, only share a top level description of what it's trying to solve. That would be a good balance in my opinion and protect your IP, even from people that are potentially interested to the point of "stealing" your ideas 😅

**Comment by Pranav-yadav** [comment]
Thank you for pointing me to that story.
I'm still learning a lot and will continue...

Private repo, would definitely be good way to achieve that.
Which I'll definitely do, and may take time.

**PS**: I'm not obsessed with IP, and I don't envy that, rather I believe in "Knowledge which is not shared is wasted!", it's just that I don't like when someone copies something without permission, that I haven't _yet_ made public, which may be because of security or other reasons.

Something _worth_ thinking: If I didn't _trust_ and _admire_ any of you and the platform, why would I be wishing to share something that has "great potential"?
I genuinely like to connect, collaborate & learn from likely minded people; doesn't matter the profession.

Apart from that, I'll work on it :)
Thanks both of you.

**Pull request merged**
